(define (make-account balance passwd)
  (let ((limit 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
            balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (incorrect-passwd amount)
      (if (>= limit 7)
        (call-the-cops)
        (begin (set! limit (+ limit 1)) "Incorrect password")))
    (define (dispatch password m)
      (if (eq? password passwd)
        (begin (set! limit 0)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request: MAKE-ACCOUNT" m))))
      incorrect-passwd))
    dispatch))